export const UPDATE_INPUT_VALIDITY = "UPDATE_INPUT_VALIDITY",
             UPDATE_INPUT_GROUP_VALIDITY = "UPDATE_INPUT_GROUP_VALIDITY",
             UPDATE_FORM_VALIDITY = "UPDATE_FORM_VALIDITY",
             UPDATE_PRISTINE = "UPDATE_PRISTINE",
             UPDATE_FORM_SUBMITTING = "UPDATE_FORM_SUBMITTING";
